aws:
  # For local development with LocalStack
  # endpoint: http://localhost:4566
  region: ${AWS_REGION:eu-west-1}
  endpoint: ${AWS_ENDPOINT:http://localhost:4566}
  access-key: ${AWS_ACCESS_KEY:test}
  secret-key: ${AWS_SECRET_KEY:test}

  dynamodb:
    table:
      tenant-info: ${AWS_DYNAMODB_TABLE:localdev_tenant_info}